### ISSUE TITLE
移至 cypherpunks.tech

### ISSUE THREAD

**Issue by ChenPoWei** [ChenPoWei/Schnorr_Signature_Resources_zh#1]
在 https://cypherpunks.tech/ 中  ，資源分類中創建新的版面，創建Schnorr簽名資源

**Comment by awesome-doge** [comment]
計畫有所改變 
已經將Schnorr簽名資源
移動到 https://cypherpunks-core.github.io/markdown/resources/resources-schnorr-signature/
